// <auto-generated />
using System;
using ADAT_Project.DataAccess.EfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADAT_Project.EfCore.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260304034139_added_UQ_index_to_setId_and_CollectorNumber_in_Printing")]
    partial class added_UQ_index_to_setId_and_CollectorNumber_in_Printing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_type");

                    b.HasKey("AuditId")
                        .HasName("PK__audit_lo__5AF33E33520C6B02");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("card_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<bool?>("IsLegendary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_legendary");

                    b.Property<string>("ManaCost")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mana_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("OracleText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oracle_text");

                    b.Property<string>("Power")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("power");

                    b.Property<string>("Rarity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rarity");

                    b.Property<string>("Toughness")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("toughness");

                    b.HasKey("CardId")
                        .HasName("PK__cards__BDF201DD93F2652B");

                    b.ToTable("cards");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.CardPrinting", b =>
                {
                    b.Property<int>("PrintingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("printing_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrintingId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("card_id");

                    b.Property<string>("CollectorNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("collector_number");

                    b.Property<int>("SetId")
                        .HasColumnType("int")
                        .HasColumnName("set_id");

                    b.HasKey("PrintingId")
                        .HasName("PK__card_pri__15FFEFA27DBF2B4F");

                    b.HasIndex("CardId");

                    b.HasIndex("SetId", "CollectorNumber")
                        .IsUnique()
                        .HasFilter("[collector_number] IS NOT NULL");

                    b.ToTable("card_printings");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Cardtype", b =>
                {
                    b.Property<int>("CardtypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cardtype_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardtypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("CardtypeId")
                        .HasName("PK__types__2C0005983128B7D4");

                    b.ToTable("cardtypes");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("color_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("ColorId")
                        .HasName("PK__colors__1143CECB01BE8A19");

                    b.ToTable("colors");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Set", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("set_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.HasKey("SetId")
                        .HasName("PK__sets__14B092A38E8A0E17");

                    b.ToTable("sets");
                });

            modelBuilder.Entity("CardCardtype", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("card_id");

                    b.Property<int>("CardtypeId")
                        .HasColumnType("int")
                        .HasColumnName("cardtype_id");

                    b.HasKey("CardId", "CardtypeId")
                        .HasName("PK__card_typ__2F320184F90159ED");

                    b.HasIndex("CardtypeId");

                    b.ToTable("card_cardtypes", (string)null);
                });

            modelBuilder.Entity("CardColor", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("card_id");

                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("color_id");

                    b.HasKey("CardId", "ColorId")
                        .HasName("PK__card_col__1CE63D317B235600");

                    b.HasIndex("ColorId");

                    b.ToTable("card_colors", (string)null);
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.CardPrinting", b =>
                {
                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Card", "Card")
                        .WithMany("CardPrintings")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__card_prin__card___5DCAEF64");

                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Set", "Set")
                        .WithMany("CardPrintings")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__card_prin__set_i__5EBF139D");

                    b.Navigation("Card");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("CardCardtype", b =>
                {
                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__card_type__card___59FA5E80");

                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Cardtype", null)
                        .WithMany()
                        .HasForeignKey("CardtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__card_type__type___5AEE82B9");
                });

            modelBuilder.Entity("CardColor", b =>
                {
                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__card_colo__card___5629CD9C");

                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__card_colo__color__571DF1D5");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Card", b =>
                {
                    b.Navigation("CardPrintings");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Set", b =>
                {
                    b.Navigation("CardPrintings");
                });
#pragma warning restore 612, 618
        }
    }
}
