// <auto-generated />
using System;
using ADAT_Project.DataAccess.EfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADAT_Project.EfCore.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260302162945_Added_unique_for_name_property__in_card_model")]
    partial class Added_unique_for_name_property__in_card_model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_type");

                    b.HasKey("AuditId");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("card_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<bool?>("IsLegendary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_legendary");

                    b.Property<string>("ManaCost")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mana_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("OracleText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oracle_text");

                    b.Property<string>("Power")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("power");

                    b.Property<string>("Rarity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rarity");

                    b.Property<string>("Toughness")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("toughness");

                    b.HasKey("CardId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_cards_name");

                    b.ToTable("cards");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.CardPrinting", b =>
                {
                    b.Property<int>("PrintingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("printing_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrintingId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("card_id");

                    b.Property<string>("CollectorNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("collector_number");

                    b.Property<int>("SetId")
                        .HasColumnType("int")
                        .HasColumnName("set_id");

                    b.HasKey("PrintingId");

                    b.HasIndex("CardId")
                        .HasDatabaseName("IX_card_printings_card_id");

                    b.HasIndex("SetId")
                        .HasDatabaseName("IX_card_printings_set_id");

                    b.ToTable("card_printings");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Cardtype", b =>
                {
                    b.Property<int>("CardtypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cardtype_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardtypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("CardtypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_types_name");

                    b.HasIndex(new[] { "Name" }, "UQ_types_name")
                        .IsUnique();

                    b.ToTable("cardtypes");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("color_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("ColorId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_colors_name");

                    b.HasIndex(new[] { "Name" }, "UQ_colors_name")
                        .IsUnique();

                    b.ToTable("colors");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Set", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("set_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.HasKey("SetId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_sets_code");

                    b.HasIndex(new[] { "Code" }, "UQ__sets__357D4CF97C5356A3")
                        .IsUnique();

                    b.ToTable("sets");
                });

            modelBuilder.Entity("CardCardtype", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("card_id");

                    b.Property<int>("CardtypeId")
                        .HasColumnType("int")
                        .HasColumnName("cardtype_id");

                    b.HasKey("CardId", "CardtypeId");

                    b.HasIndex("CardtypeId")
                        .HasDatabaseName("IX_card_cardtypes_cardtype_id");

                    b.ToTable("card_cardtypes", (string)null);
                });

            modelBuilder.Entity("CardColor", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("card_id");

                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("color_id");

                    b.HasKey("CardId", "ColorId");

                    b.HasIndex("ColorId")
                        .HasDatabaseName("IX_card_colors_color_id");

                    b.ToTable("card_colors", (string)null);
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.CardPrinting", b =>
                {
                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Card", "Card")
                        .WithMany("CardPrintings")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Set", "Set")
                        .WithMany("CardPrintings")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("CardCardtype", b =>
                {
                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Cardtype", null)
                        .WithMany()
                        .HasForeignKey("CardtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardColor", b =>
                {
                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ADAT_Project.DataAccess.EfCore.Entities.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Card", b =>
                {
                    b.Navigation("CardPrintings");
                });

            modelBuilder.Entity("ADAT_Project.DataAccess.EfCore.Entities.Set", b =>
                {
                    b.Navigation("CardPrintings");
                });
#pragma warning restore 612, 618
        }
    }
}
